# 09_export_apkg.py (v2.1)
#
# Generates a high-quality Anki deck based on the AnkiDKDeck V2.1 pipeline.
# Key Features:
# - One Card Per Word: Each query_word gets a single, unified Anki card.
# - Priority Sorting: Homograph meanings are sorted by commonality using priority_map.json.
# - Progressive Disclosure: Uses <details> tags to intelligently fold less critical information.
# - Enhanced Front Side: Pronunciations grouped by Part-of-Speech.
# - Prominent Collocations: Fixed expressions are now a dedicated, visible section.
# - Backward Compatibility: Maintains GUID generation logic to preserve user study progress.

import json
import zlib
from pathlib import Path
from collections import defaultdict

import genanki

# --- Configuration ---
# Input files from the V2 pipeline
DDO_ENTRIES_FILE = "ddo_entries.json"
TARGET_LANG = "Spanish"  # Set your target language here
PRIORITY_MAP_FILE = "priority_map.json"
AUDIO_MAP_FILE = "audio_map.json"
POS_TRANSLATIONS_FILE_TEMPLATE = "pos_translations_{TARGET_LANG}_gemini.json"


# --- Dynamic File Paths & Deck Info ---
def_trans_path = Path(f"definition_translations_{TARGET_LANG}_gemini-2.0-flash.json")
expr_trans_path = Path(f"expression_translations{TARGET_LANG}_gemini-2.0-flash.json")
pos_trans_def_path = Path(
    POS_TRANSLATIONS_FILE_TEMPLATE.format(TARGET_LANG=TARGET_LANG)
)  # New
output_apkg_path = Path(f"DDO_Danish_Frequency_Deck_{TARGET_LANG}.apkg")


# --- Static Deck Configuration & Templates ---
# Fixed copyright year: the released decks were built in 2025, and a fixed
# value keeps rebuilds byte-identical to the published .apkg files.
COPYRIGHT_YEAR = 2025
LANG_HASH = zlib.adler32(TARGET_LANG.encode("utf-8")) & 0x7FFFFFFF
DECK_ID_BASE = 0x10000000
MODEL_ID_BASE = 0x20000000

DECK_ID = DECK_ID_BASE + LANG_HASH
MODEL_ID = MODEL_ID_BASE + LANG_HASH

# Handle compatibility for specific languages if needed
if TARGET_LANG.lower() == "chinese":
    DECK_ID = 1745409457359
    deck_name = "丹麦语要你命3000词"
    deck_description = f"""<p>本牌组是基于丹麦语词频列表生成的 Anki 卡片。</p><p><b>数据来源说明:</b></p><ul><li>词频列表主要参考: <a href="https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Danish_wordlist">Wiktionary Danish Frequency List</a></li><li>如果您从Den Danske Ordbog 获取单词定义、发音、例句等数据部分，请注意遵守 DDO 的使用条款，仅供您个人使用，切勿分享。</li><li>部分翻译由人工智能辅助生成，仅供参考。</li></ul><p><b>版权与许可:</b></p><ul><li>Wiktionary 内容遵循 CC BY-SA 3.0 许可。</li><li>本 Anki 牌组生成脚本及牌组结构由 iskoldt-X 创建 (© {COPYRIGHT_YEAR})。</li></ul><p><b>项目代码仓库:</b></p><p><a href="https://github.com/iskoldt-X/ankidkdeck">https://github.com/iskoldt-X/ankidkdeck</a></p><p>如果您觉得这个牌组有用，欢迎⭐️项目或捐赠，欢迎提出改进建议！</p>"""
    COPYRIGHT_HTML = f"""
    <div class="copyright-info" style="font-size: 0.8em; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px;">
        <small>
            使用 <a href="https://github.com/iskoldt-X/ankidkdeck" style="color: #55a;">ankidkdeck</a> 生成<br>
            Copyright © {COPYRIGHT_YEAR} iskoldt-X<br>
            如果您喜欢这个牌组，请考虑⭐本项目或捐赠
        </small>
    </div>
    """
else:
    deck_name = f"Avadanskedavra: 3000 Words to Slay {TARGET_LANG}"
    deck_description = f"""<p>This deck is generated from a Danish frequency list as Anki cards.</p><p><b>Data Sources:</b></p><ul><li>Frequency list primarily based on: <a href="https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Danish_wordlist">Wiktionary Danish Frequency List</a></li><li>If you get the word definitions, pronunciation, examples, etc. from Den Danske Ordbog (DDO). Please respect DDO’s terms of use—for personal study only, do not redistribute.</li><li>Translations are generated by AI and provided for reference only.</li></ul><p><b>Copyright & License:</b></p><ul><li>Wiktionary content is available under CC BY‑SA 3.0.</li><li>This Anki deck generation script and deck structure were created by iskoldt‑X (© {COPYRIGHT_YEAR}).</li></ul><p><b>Project Repository:</b></p><p><a href="https://github.com/iskoldt-X/ankidkdeck">https://github.com/iskoldt-X/ankidkdeck</a></p><p>If you find this deck useful, please feel free to ⭐ the project or open issues/suggestions!</p>"""

    COPYRIGHT_HTML = f"""
    <div class="copyright-info" style="font-size: 0.8em; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px;">
        <small>
            Generated using <a href="https://github.com/iskoldt-X/ankidkdeck" style="color: #55a;">ankidkdeck</a><br>
            Copyright © {COPYRIGHT_YEAR} iskoldt-X<br>
            If you like this deck, please consider ⭐ the project or donating
        </small>
    </div>
    """

# --- Anki Model Definition ---
FIELDS = [
    {"name": "QueryWord"},
    {"name": "FrontSideSummary"},  # New, replaces Pronunciations
    {"name": "Content"},
    {"name": "Collocations"},  # New
    {"name": "Variants"},
    {"name": "Derivatives"},
    {"name": "Etymology"},
    {"name": "FrequencyRank"},
]

CSS = """
.card { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.5; text-align: left; color: #333; }
.front-container { text-align: center; }
.query-word { font-size: 3em; font-weight: 600; }
.ipa-row { display: block; margin: 0 10px; padding: 3px 0; } /* Changed from inline-flex, made display: block */
.replay-button svg { width:22px; height:22px; vertical-align:middle; margin-left:5px; }
.meaning-block { margin-bottom: 20px; padding: 15px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #fcfcfc; }
.meaning-block:last-child { margin-bottom: 0; }
.meaning-header { font-size: 1.2em; font-weight: 600; color: #005a9c; margin-bottom: 10px; }
.pos { font-style: italic; color: #666; margin-left: 8px; font-weight: normal; }
.definition-item { margin-bottom: 12px; }
.def-text { display: block; }
.translation { color: #2e7d32; font-size: 0.95em; margin-left: 1.2em; }
.example { color: #757575; font-size: 0.9em; margin-left: 1.2em; border-left: 2px solid #d0d0d0; padding-left: 8px; margin-top: 4px; }
details > summary { list-style: none; } 
details > summary::-webkit-details-marker { display: none; } 
.details-toggle { cursor: pointer; color: #0066cc; font-size: 0.9em; margin-top: 10px; }
.hr-divider { border: 0; height: 1px; background: #ddd; margin: 20px 0; }
.bottom-info { font-size: 0.9em; color: #666; margin-top: 20px; padding-top: 10px; border-top: 1px solid #eee; }
.freq-rank { font-size: 0.8em; color: #aaa; text-align: right; float: right; }

/* --- NEW CSS FOR V2.1 --- */
.summary-divider { border: 0; height: 1px; background: #ddd; margin: 15px 0; }
.summary-divider-inner { border: 0; height: 1px; background: #eee; margin: 10px 0 10px 10px; } /* Added left margin */
.summary-content { font-size: 1.0em; color: #444; text-align: left; max-width: 600px; margin: 0 auto; padding: 0 10px; } /* Added padding */
.pos-group { margin-bottom: 10px; }
.pos-group:last-child { margin-bottom: 0; }
.pos-group-header { font-size: 1.1em; font-weight: 600; color: #005a9c; margin-bottom: 5px; }
.collocations-container { margin-top: 20px; margin-bottom: 20px; padding: 15px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #fcfcfc; }
.collocations-header { font-size: 1.2em; font-weight: 600; color: #005a9c; margin-bottom: 10px; }


/* --- NIGHT MODE OVERRIDES --- */
.night_mode .card { color: #f0f0f0; }
.night_mode .query-word { color: #ffffff; }
.night_mode .ipa-row { color: #cccccc; }
.night_mode .meaning-block { background-color: #2e2e2e; border: 1px solid #444; }
.night_mode .meaning-header { color: #8ab4f8; }
.night_mode .pos { color: #aaa; }
.night_mode .translation { color: #81c784; }
.night_mode .example { color: #9e9e9e; border-left: 2px solid #555; }
.night_mode .details-toggle { color: #82aaff; }
.night_mode .hr-divider { background: #444; }
.night_mode .bottom-info { color: #b0b0b0; border-top: 1px solid #444; }

/* --- NEW NIGHT MODE CSS FOR V2.1 --- */
.night_mode .summary-divider { background: #444; }
.night_mode .summary-divider-inner { background: #383838; }
.night_mode .summary-content { color: #ccc; }
.night_mode .pos-group-header { color: #8ab4f8; }
.night_mode .collocations-container { background-color: #2e2e2e; border: 1px solid #444; }
.night_mode .collocations-header { color: #8ab4f8; }
"""

QFMT = """
<div class="front-container">
  <div class="query-word">{{QueryWord}}</div>
  <hr class="summary-divider">
  <div class="summary-content">{{FrontSideSummary}}</div>
</div>
"""
AFMT = (
    """
{{FrontSide}}
<hr class="hr-divider">
<div>{{Content}}</div>
{{#Collocations}}
<div class="collocations-container">
    <div class="collocations-header">Fixed Expressions</div>
    {{Collocations}}
</div>
{{/Collocations}}
<div class="bottom-info">
  <div class="freq-rank">Rank: {{FrequencyRank}}</div>
  {{#Variants}}<b>Variants:</b> {{Variants}}<br>{{/Variants}}
  {{#Derivatives}}<b>Derivatives:</b> {{Derivatives}}<br>{{/Derivatives}}
  {{#Etymology}}<b>Etymology:</b> {{Etymology}}{{/Etymology}}
</div>
"""
    + COPYRIGHT_HTML
    + """
    <script>
    (function () {
      const MORE = "Show more definitions...";
      const LESS = "Show less...";

      // Ensure cards initially start with <details> closed.
      // Using the more general selector as provided by ChatGPT's tested solution.
      document.querySelectorAll("details[open]").forEach(d => {
        // We only want to close the <details> elements that use our specific toggle class.
        // This avoids accidentally closing other <details> elements if they exist.
        if (d.querySelector("summary.details-toggle")) {
            d.removeAttribute("open");
        }
      });

      // Initialize all relevant summary texts to the "MORE" state.
      // Using the more general selector as provided by ChatGPT's tested solution.
      document.querySelectorAll("summary.details-toggle").forEach(s => { 
        s.textContent = MORE; 
      });

      // Use event delegation on the document for click events
      document.addEventListener("click", e => {
        // Find the closest summary.details-toggle that was clicked or contains the click target
        const summary = e.target.closest("summary.details-toggle");
        
        // If the click was not on or inside a relevant summary, do nothing
        if (!summary) return;

        const details = summary.parentElement; // The <details> element

        // requestAnimationFrame waits for the browser to complete its native open/close action
        // and update the 'open' attribute before we read it.
        requestAnimationFrame(() => {
          summary.textContent = details.open ? LESS : MORE;
        });
      }, true); // Using capture phase for the listener on document
    })();
    </script>
"""
)

MODEL = genanki.Model(
    MODEL_ID,
    f"Danish Frequency Deck V2.1 ({TARGET_LANG})",  # Model name updated
    fields=FIELDS,
    templates=[{"name": "Card 1", "qfmt": QFMT, "afmt": AFMT}],
    css=CSS,
    sort_field_index=7,  # Sort by FrequencyRank (index changed from 6 to 7)
)

# --- Helper Functions ---


def load_json(filepath, default_val=None):
    """Safely loads a JSON file."""
    if default_val is None:
        default_val = {}
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        print(f"Warning: Could not load or parse {filepath}. Using default value.")
        return default_val


def sanitize(text):
    """Basic text cleaning."""
    return str(text).strip() if text is not None else ""


def get_frequency_list():
    """Fetches the frequency list from your local files, as the download script already did this."""
    download_map = load_json("download_map.json")
    if not download_map:
        print(
            "Error: download_map.json is missing or empty. Cannot determine frequency."
        )
        return []
    word_rank_list = []
    processed_words = set()
    for entry_info in download_map.values():
        word = entry_info.get("query_word")
        rank = entry_info.get("query_rank")
        if (
            word and rank is not None and word not in processed_words
        ):  # Check rank is not None
            word_rank_list.append((rank, word))
            processed_words.add(word)
    word_rank_list.sort(key=lambda x: x[0])
    return [word for rank, word in word_rank_list]


def build_pronunciations_html_for_group(entries_for_pos, audio_map):
    """
    Builds a unique list of pronunciations for a specific group of entries (e.g., for one POS).
    Each pronunciation will be a block element.
    """
    seen_ipas, rows = set(), []
    for entry in entries_for_pos:
        for u in entry.get("udtale", []):
            ipa_raw = sanitize(u.get("ipa", "")).strip("[]").strip()
            if not ipa_raw or ipa_raw in seen_ipas:
                continue
            seen_ipas.add(ipa_raw)
            label_html = (
                f'<span class="ipa-label">({sanitize(u.get("label"))})</span>'
                if u.get("label")
                else ""
            )
            audio_url, sound_tag = u.get("audio", ""), ""
            if audio_url and audio_url in audio_map:
                audio_filename = Path(audio_map[audio_url]).name
                sound_tag = f"[sound:{audio_filename}]"
            rows.append(
                f'<div class="ipa-row">[{ipa_raw}] {label_html} {sound_tag}</div>'
            )
    return "".join(rows)


def build_front_summary_html(sorted_entries, audio_map, pos_translations):
    """Builds HTML for the front side summary, grouping pronunciations by POS."""
    if not sorted_entries:
        return ""

    pos_groups = defaultdict(list)
    # Use a default POS if entry["pos"] is missing or empty
    default_pos_key = "Uncategorized"

    for entry in sorted_entries:
        pos = sanitize(entry.get("pos"))
        if not pos:  # Handles None or empty string after sanitize
            pos = default_pos_key
        pos_groups[pos].append(entry)

    html_parts = []

    # Maintain the order of POS appearance from sorted_entries for primary sorting of groups
    ordered_pos_keys = []
    seen_pos_for_order = set()
    for entry in sorted_entries:
        pos = sanitize(entry.get("pos"))
        if not pos:
            pos = default_pos_key
        if pos not in seen_pos_for_order:
            ordered_pos_keys.append(pos)
            seen_pos_for_order.add(pos)

    # Ensure all keys from pos_groups are in ordered_pos_keys if some entries had no POS initially
    # but were grouped under default_pos_key
    if default_pos_key in pos_groups and default_pos_key not in ordered_pos_keys:
        # Add it, but its exact position might be arbitrary if no entry explicitly had it.
        # This case is less likely if default_pos_key is only used when sanitize(entry.get("pos")) is empty.
        ordered_pos_keys.append(default_pos_key)

    if len(ordered_pos_keys) == 1:  # Single POS group (or all uncategorized)
        pos_key = ordered_pos_keys[0]
        entries_for_pos = pos_groups[pos_key]

        pos_display = (
            pos_key if pos_key != default_pos_key else ""
        )  # Don't display "Uncategorized" literally unless it's the only info
        translated_pos = (
            pos_translations.get(pos_key, "") if pos_key != default_pos_key else ""
        )

        header_text = pos_display
        if translated_pos:
            header_text += f" ({translated_pos})"

        pos_header_html = (
            f'<div class="pos-group-header">{header_text}</div>'
            if header_text.strip()
            else ""
        )
        pron_html = build_pronunciations_html_for_group(entries_for_pos, audio_map)

        if pos_header_html or pron_html:
            html_parts.append(
                f'<div class="pos-group">{pos_header_html}{pron_html}</div>'
            )

    else:  # Multiple POS groups
        for pos_key in ordered_pos_keys:
            if pos_key not in pos_groups:
                continue  # Should not happen with current logic

            entries_for_pos = pos_groups[pos_key]

            pos_display = (
                pos_key if pos_key != default_pos_key else "Other"
            )  # Or some other neutral term
            translated_pos = pos_translations.get(pos_key, "")

            header_text = pos_display
            if translated_pos:
                header_text += f" ({translated_pos})"

            # Only create header if there's actual text for it
            pos_header_html = (
                f'<div class="pos-group-header">{header_text}</div>'
                if header_text.strip()
                else ""
            )
            pron_html = build_pronunciations_html_for_group(entries_for_pos, audio_map)

            if pos_header_html or pron_html:
                html_parts.append(
                    f'<div class="pos-group">{pos_header_html}{pron_html}</div>'
                )

    return '<hr class="summary-divider-inner">'.join(filter(None, html_parts))


def build_content_html(entries, def_trans):
    """The core function to generate the folded HTML content for the card's back (definitions and examples only)."""
    all_meaning_blocks = []

    for entry in entries:
        filename = entry.get("filename")
        if not filename:
            continue
        entry_def_trans = def_trans.get(filename, {})
        definitions_html = []

        for i, d in enumerate(entry.get("definitions", [])):
            def_text = sanitize(d.get("definition"))
            if not def_text:
                continue
            translation_html, example_html = "", ""
            if trans_data := entry_def_trans.get(def_text):
                lemma, gloss = sanitize(trans_data.get("lemma")), sanitize(
                    trans_data.get("gloss")
                )
                translation_html = (
                    f'<div class="translation"><b>{lemma}</b>: {gloss}</div>'
                )

            if examples := d.get("examples"):
                if first_ex_text := sanitize(examples[0].get("text")):
                    example_html = f'<div class="example">E.g., "{first_ex_text}"</div>'

            definitions_html.append(
                f'<div class="definition-item"><span class="def-text">{i+1}. {def_text}</span>{translation_html}{example_html}</div>'
            )

        if not definitions_html:
            continue

        pos_html = (
            f'<span class="pos">{sanitize(entry.get("pos"))}</span>'
            if entry.get("pos")
            else ""
        )
        headword_display = sanitize(entry.get("headword"))
        block_header = (
            f'<div class="meaning-header">{headword_display} {pos_html}</div>'
        )

        visible_content = "".join(definitions_html[:2])
        folded_content = "".join(definitions_html[2:])

        details_html = ""
        if folded_content:
            details_html = f"""
            <details>
              <summary class="details-toggle">Show more definitions...</summary>
              <div style="margin-top: 10px;">{folded_content}</div>
            </details>
            """

        all_meaning_blocks.append(
            f'<div class="meaning-block">{block_header}{visible_content}{details_html}</div>'
        )

    return '<hr class="hr-divider">'.join(all_meaning_blocks)


def build_collocations_html(sorted_entries, expr_translations):
    """Builds HTML for the 'Fixed Expressions' (Collocations) section."""
    all_expressions_html = []
    seen_expressions_text = set()

    for entry in sorted_entries:
        filename = entry.get("filename")
        if not filename:
            continue

        entry_expr_trans = expr_translations.get(filename, {})

        for fx in entry.get("fixed_expressions", []):
            expr_text = sanitize(fx.get("expression"))
            if not expr_text or expr_text in seen_expressions_text:
                continue

            seen_expressions_text.add(expr_text)
            translation_html = ""
            if trans_data := entry_expr_trans.get(expr_text):
                lemma = sanitize(trans_data.get("lemma"))
                gloss = sanitize(trans_data.get("gloss"))
                if lemma or gloss:
                    translation_html = (
                        f'<div class="translation"><b>{lemma}</b>: {gloss}</div>'
                    )

            all_expressions_html.append(
                f'<div class="definition-item">{expr_text}{translation_html}</div>'
            )  # Using .definition-item style for consistency

    return "".join(all_expressions_html) if all_expressions_html else ""


# --- Main Execution ---
if __name__ == "__main__":
    print("--- AnkiDKDeck V2.1 Exporter ---")  # Version updated

    # 1. Load all data
    print("Loading data files...")
    all_entries = load_json(DDO_ENTRIES_FILE, [])
    def_translations = load_json(def_trans_path)
    expr_translations = load_json(expr_trans_path)
    priority_map = load_json(PRIORITY_MAP_FILE)
    audio_map = load_json(AUDIO_MAP_FILE)
    pos_translations = load_json(pos_trans_def_path)  # New

    if not all_entries:
        print("Error: ddo_entries.json is empty or missing. Aborting.")
        exit(1)

    # 2. Group entries by query_word
    print("Grouping entries by query word...")
    grouped_by_word = defaultdict(list)
    for entry in all_entries:
        if query_word := entry.get("query_word"):
            grouped_by_word[query_word].append(entry)

    # 3. Get frequency-sorted list of words
    print("Getting frequency-sorted word list...")
    frequency_list = get_frequency_list()
    if not frequency_list:
        frequency_list = sorted(grouped_by_word.keys())
        print("Warning: Using alphabetical order due to missing/failed frequency data.")

    # 4. Create Anki deck and prepare for media files
    deck = genanki.Deck(DECK_ID, deck_name, description=deck_description)
    media_files = set()

    # 5. Main loop: iterate through words and generate notes
    print(f"Generating notes for {len(frequency_list)} unique words...")
    word_to_rank_map = {word: i + 1 for i, word in enumerate(frequency_list)}

    for query_word in frequency_list:
        entries_for_word = grouped_by_word.get(query_word)
        if not entries_for_word:
            continue

        if priority_order := priority_map.get(query_word):
            filename_to_entry = {e["filename"]: e for e in entries_for_word}
            sorted_entries = [
                filename_to_entry[fname]
                for fname in priority_order
                if fname in filename_to_entry
            ]
            # Add any entries not in priority_order (e.g. new entries) to the end
            # This ensures all entries are processed.
            remaining_entries = [
                e for e in entries_for_word if e["filename"] not in priority_order
            ]
            sorted_entries.extend(remaining_entries)

        else:
            sorted_entries = entries_for_word

        if not sorted_entries:  # Should not happen if entries_for_word was not empty
            continue

        primary_entry = sorted_entries[0]

        # New: FrontSideSummary HTML
        front_summary_html = build_front_summary_html(
            sorted_entries, audio_map, pos_translations
        )

        # Modified: Content HTML (definitions and examples only)
        content_html = build_content_html(sorted_entries, def_translations)

        # New: Collocations HTML
        collocations_html = build_collocations_html(sorted_entries, expr_translations)

        variants = "; ".join(map(sanitize, primary_entry.get("wordforms", [])))
        etymology_data = primary_entry.get("etymology")
        etymology = sanitize(etymology_data.get("raw", "")) if etymology_data else ""

        derivs = []
        for entry in sorted_entries:  # Collect from all entries for the query_word
            od = entry.get("orddannelser", {})
            derivs.extend(od.get("Afledninger", []))
            derivs.extend(od.get("Sammensætninger", []))
        derivatives = ", ".join(
            map(sanitize, sorted(list(set(d for d in derivs if d))))
        )  # Ensure no None/empty strings

        freq_rank = word_to_rank_map.get(query_word, "")

        for entry in sorted_entries:
            for u in entry.get("udtale", []):
                if audio_url := u.get("audio"):
                    if audio_path_str := audio_map.get(audio_url):
                        media_files.add(audio_path_str)

        guid = genanki.guid_for(query_word, TARGET_LANG)  # GUID logic unchanged

        note = genanki.Note(
            model=MODEL,
            fields=[
                query_word,
                front_summary_html,
                content_html,
                collocations_html,
                variants,
                derivatives,
                etymology,
                str(freq_rank),
            ],
            guid=guid,
        )
        deck.add_note(note)

    # 6. Package and save the deck
    print("Packaging Anki deck...")
    pkg = genanki.Package(deck)
    existing_media_files = [mf for mf in media_files if Path(mf).exists()]
    pkg.media_files = existing_media_files

    pkg.write_to_file(output_apkg_path)

    print("\n--- Generation Complete! ---")
    print(f"✓ Deck saved to: {output_apkg_path}")
    print(f"  - Cards: {len(deck.notes)}")
    print(f"  - Media Files: {len(existing_media_files)}")
    if len(media_files) != len(existing_media_files):
        print(
            f"  - Warning: {len(media_files) - len(existing_media_files)} media files were mapped but not found on disk."
        )
